In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from os import listdir

bin_path = '/Users/harihara/Mount/projects/refining_bins_with_assembly_graphs/Scaffold_Coverage_binning/delinked_scaffold_bins/'
coverage_path = '/Users/harihara/Research-Activities/Data/Binnacle-Op/Scaffold_Coverage_After_Delinking/'

In [5]:
def Is_Scaffold(Scaffold_ID):
    if 'cc_' in Scaffold_ID:
        return 'Scaffold'
    else:
        return 'Contig'
    
def Get_Scaffolds(sample):
    df = pd.read_csv(bin_path+sample+'_delinked_cc_bins/'+sample+'_delinked_cc', 
                     sep = '\t', names = ['Connected_Component_After_Delinking', 'Bin_ID'])
    df['Type'] = df['Connected_Component_After_Delinking'].apply(Is_Scaffold)
    df['Connected_Component_After_Delinking'] = df['Connected_Component_After_Delinking'].str.replace("cc_","")
    return df

def Load_Coverage_Summary(sample):
    df_cov = pd.read_csv(coverage_path+sample+'_Coverages.csv_Summary.csv', index_col = ['Connected_Component'])
    return df_cov

In [6]:
df_bins = Get_Scaffolds('SRS104485')

In [7]:
df_cov_summary = Load_Coverage_Summary('SRS104485')

In [8]:
df_bins.join(df_cov_summary)

,Connected_Component_After_Delinking,Bin_ID,Type,Mean,Dev
0,1,573,Scaffold,NaN,NaN
1,2,278,Scaffold,9.480152,3.970458
2,3,2276,Scaffold,15.413903,4.875709
3,4,63,Scaffold,9.281558,3.451367
4,5,0,Scaffold,15.204052,7.439948
...,...,...,...,...,...
7899,contig-100_675.48359,0,Contig,NaN,NaN
7900,contig-100_689.48373,0,Contig,NaN,NaN
7901,contig-100_690.48374,0,Contig,NaN,NaN
7902,contig-100_700.48384,0,Contig,NaN,NaN
7903,contig-100_703.48387,0,Contig,NaN,NaN